name: Build master branch

on:
  push:
    branches:
      - master

jobs:
  publish-release:
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.8.1
      - name: Execute Gradle build
        env:
          MAVENCENTRALUSERNAME: ${{ secrets.MAVENCENTRALUSERNAME }}
          MAVENCENTRALPASSWORD: ${{ secrets.MAVENCENTRALPASSWORD }}
          SIGNINGKEY: ${{ secrets.SIGNINGKEY }}
          SIGNINGPASSWORD: ${{ secrets.SIGNINGPASSWORD }}
        run: ./gradlew publishToSonatype closeAndReleaseStagingRepository
