name: Publish release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.8.1

      - name: Execute Gradle build
        env:
          MAVENCENTRALUSERNAME: ${{ secrets.MAVENCENTRALUSERNAME }}
          MAVENCENTRALPASSWORD: ${{ secrets.MAVENCENTRALPASSWORD }}
          SIGNINGKEY: ${{ secrets.SIGNINGKEY }}
          SIGNINGPASSWORD: ${{ secrets.SIGNINGPASSWORD }}
        run: ./gradlew build

  release-notes:
    runs-on: ubuntu-20.04
    steps:
      - name: Release Drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
